### ISSUE TITLE
error when running `list-uninstalled` option (pi-apps different name I think)

### ISSUE THREAD

**Issue by Itai-Nelken** [techcoder20/PiAppsPackageManagerTerminal#5]
installed from pi-apps.
```bash
pi@twisterpi-4-4gb:~ $ pi-apps list-uninstalled
PiAppsTerminalAdvanced
Traceback (most recent call last):
  File "/home/pi/pi-apps/PiAppsTerminalAdvanced.py", line 184, in <module>
    list_uninstalled()
  File "/home/pi/pi-apps/PiAppsTerminalAdvanced.py", line 58, in list_uninstalled
    descriptionfile = open("/home/pi/pi-apps/apps/" + InstalledApp + "/description","r")
FileNotFoundError: [Errno 2] No such file or directory: '/home/pi/pi-apps/apps/PiAppsTerminalAdvanced/description'
pi@twisterpi-4-4gb:~ $ 
```

can the issue be that its called `Pi-Apps Terminal Plugin` in pi-apps now? because the file its looking for is here: `/home/pi/pi-apps/apps/Pi-Apps Terminal Plugin/description`.

**Comment by techcoder20** [comment]
Yes that's the problem. You must have downloaded the testing zip when the name was PiAppsTerminalAdvanced. When you installed it created a file with that name in the data folder due to which this error occurs. For the time being you can manually remove that file from the data folder. I will try to automate this in the future
